%
% Copyright 2010/2011 Juergen Humt
% 
% This file is part of RotaryWingSim.
% 
%     RotaryWingSim, is free  software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by the 
%     Free Software Foundation, either version 3 of the License or any later 
%     version.
% 
%     RotaryWingSim is distributed in the hope that it will be useful,
%     but WITHOUT ANY WARRANTY; without even the implied warranty of
%     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%     GNU General Public License for more details.
% 
%     You should have received a copy of the GNU General Public License along 
%     with RotaryWingSim.  If not, see <http://www.gnu.org/licenses/>.
%
%
%  Version 1.0 of this program was based on report naca-tm-73254 
%
%         --- Version 1.2 ---
%
% 
% This modul is a list of all global data, a sort of common block
% 
% Input:
%  none
%
% Output:
%  none
% 

 global gEarth rhoAir kinVisc f2m i2m slg2kg lbMass lbForce bTl xNr gamRot...
    DvLRes cLsRes aLift cHMR dNMR cMI sigma fpA aBlade roL vFlight mHeliG mHeli addLd...
    aDiskMR oM oMTrim oMR qMR rRot iRigMR iBlade nB eRot xGBlade wBlade mRot DvLpGlo cDrgGlo cLftGlo...
    nRot nRotMin thta1 dDrgN dDrg1 dDrg2 thtaClmb cDPoly cMPoly zPA zPB doTest cMIN...
    vFlight cTsReq cT2sA lamI hRotCG fRotCG cMs cMI xcg lmd xCG...
    lWN hWN aWing bWing CdMax cRwing cTwing alpnWing iRigWing aLiftWing CLwngGlo CDwngGlo...
    AlphaEnd AlphaZL numData ClData CdData CmData ReData numRe...
    vTail bHS areaHS  aLiftHS lHS hHS iRigHS lVS hVS lTail iRigTail etaDwn vhv1 vfv1...
    areaVSfin aLiftVSfin CLvert CDovert CDalf9N lVF hVF...
    tauProp hPR lPR propDia engineHP engineRPM pCTP...
    aN dNMR d2 aDiskTR oMTR oMRTR rRotTR muTR sigmaTR aLiftTR gamRotTR...
    C1 C4 C5 C6 C7 C8 T1 T2 T3 T4 T5 F1 kG...
    k1 k2 D1 D2 D3 H1 H2 H4 L1 M1 M1a N1 Y1 pcMP...
    kB tauB tauR tauC B1CL A1CL...
    hMR lmd xCG xcg lTR hTR lHS...
    thtaN A1S B1S dle dla dlc dlp aNCff a1Cff b1Cff laCff cTCff rrpmCff cLpwrCff cDpwrCff ...
    vE qE uX uY uZ pB qB rB thtaTrim phiTrim psiTrim...
    Ixx Iyy Izz Ixz Sref lref f2m i2m cmNfus...
    ClFus CyFus CdFus CmFus CnFus clNfus cmNfus detafdalpfh zPA zPB... 
    hfus lfus yfus afV afH...
    dle2dlsP dleOffs dleMax dleMin fiHsMin fiHsMax...
    tStp dTstp dStp epsGlo fStp1 dlpArry dlpSlct...
    pE vE qE aE firstOut firstOutB nxT jTOut...
    dDrgJet dJet aJet rOutr rInnr rCntr jtCoeff...
    firstOutC logFile fStp simTime octRun gloVars fusDatFlName itrType...
    twstData cGA Gmod CmPrfl cTCx...
    clcCT_hndl clcRtAngl_hndl t31 t32 t33 pwrCalcVar
    
